### ISSUE TITLE
Unrecognized escape sequence character on start of terminal

### ISSUE THREAD

**Issue by MaxRis** [jumptrading/aminal#2] opened 2018-12-18 10:26 UTC
**Describe the bug**
On start of terminal input reading application receives 0x"\x00" and can't process it correctly.

**To Reproduce**
1. Start application on Windows with `--shell cmd.exe` command line

**Logs**
```
2018-12-14T00:07:55.712+0200	WARN	gui/gui.go:359	Failed to create window: Failed to create window using OpenGL v4.6: VersionUnavailable: WGL: Driver does not support OpenGL version 4.6.. Will attempt older version...
github.com/liamg/aminal/gui.(*GUI).createWindow
	C:/Users/max/go/src/github.com/liamg/aminal/gui/gui.go:359
github.com/liamg/aminal/gui.(*GUI).Render
	C:/Users/max/go/src/github.com/liamg/aminal/gui/gui.go:114
main.main
	C:/Users/max/go/src/github.com/liamg/aminal/main.go:56
runtime.main
	C:/Go/src/runtime/proc.go:201
2018-12-14T00:07:55.719+0200	WARN	gui/gui.go:359	Failed to create window: Failed to create window using OpenGL v4.5: VersionUnavailable: WGL: Driver does not support OpenGL version 4.5.. Will attempt older version...
github.com/liamg/aminal/gui.(*GUI).createWindow
	C:/Users/max/go/src/github.com/liamg/aminal/gui/gui.go:359
github.com/liamg/aminal/gui.(*GUI).Render
	C:/Users/max/go/src/github.com/liamg/aminal/gui/gui.go:114
main.main
	C:/Users/max/go/src/github.com/liamg/aminal/main.go:56
runtime.main
	C:/Go/src/runtime/proc.go:201
2018-12-14T00:07:55.768+0200	DEBUG	gui/gui.go:120	Initialising OpenGL and creating program...
2018-12-14T00:07:55.771+0200	INFO	gui/gui.go:409	OpenGL version 4.4.0 - Build 21.20.16.4664
2018-12-14T00:07:55.771+0200	DEBUG	gui/gui.go:411	Compiling shaders...
2018-12-14T00:07:55.778+0200	DEBUG	gui/gui.go:129	Loading font...
2018-12-14T00:07:55.803+0200	DEBUG	gui/gui.go:68	Initiating GUI resize to 800x600
2018-12-14T00:07:55.803+0200	DEBUG	gui/gui.go:73	Updating font resolutions...
2018-12-14T00:07:55.826+0200	DEBUG	gui/gui.go:76	Setting renderer area...
2018-12-14T00:07:55.827+0200	DEBUG	gui/gui.go:79	Calculating size in cols/rows...
2018-12-14T00:07:55.827+0200	DEBUG	gui/gui.go:82	Resizing internal terminal...
2018-12-14T00:07:55.827+0200	DEBUG	gui/gui.go:87	Setting viewport size...
2018-12-14T00:07:55.827+0200	DEBUG	gui/gui.go:92	Resize complete!
2018-12-14T00:07:55.827+0200	DEBUG	gui/gui.go:156	Starting pty read handling...
2018-12-14T00:07:55.827+0200	DEBUG	gui/gui.go:166	Starting render...
2018-12-14T00:07:55.828+0200	DEBUG	terminal/output.go:91	0x"\x1b"
2018-12-14T00:07:55.828+0200	DEBUG	terminal/csi.go:84	CSI 0x4A (ESC[2J) Erase in Display (ED), VT100 - 0,0 -> 0,0
2018-12-14T00:07:55.828+0200	DEBUG	terminal/output.go:91	0x"\x1b"
2018-12-14T00:07:55.828+0200	DEBUG	terminal/csi.go:84	CSI 0x6C (ESC[?25l) Reset Mode (RM) - 0,0 -> 0,0
2018-12-14T00:07:55.828+0200	DEBUG	terminal/output.go:91	0x"\x1b"
2018-12-14T00:07:55.828+0200	DEBUG	terminal/csi.go:84	CSI 0x6D (ESC[m) Character Attributes (SGR) - 0,0 -> 0,0
2018-12-14T00:07:55.828+0200	DEBUG	terminal/output.go:91	0x"\x1b"
2018-12-14T00:07:55.828+0200	DEBUG	terminal/csi.go:84	CSI 0x48 (ESC[H) Cursor Position [row;column] (default = [1,1]) (CUP) - 0,0 -> 0,0
2018-12-14T00:07:55.828+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.828+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.828+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.828+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.828+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.828+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.828+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.828+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.829+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\r"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\n"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\x1b"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/csi.go:84	CSI 0x48 (ESC[H) Cursor Position [row;column] (default = [1,1]) (CUP) - 0,29 -> 0,0
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\x1b"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"W"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"I"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"N"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"D"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"O"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"W"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"S"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\\"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"S"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"Y"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"S"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"T"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"E"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"M"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"3"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"2"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\\"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"c"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"m"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"d"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"."
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"e"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"x"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"e"
2018-12-14T00:07:55.830+0200	DEBUG	terminal/output.go:91	0x"\x00"
2018-12-14T00:07:55.830+0200	ERROR	terminal/output.go:106	Non-readable rune received: 0x%X0
```

**Comment by rrrooommmaaa** [comment] 2018-12-23 13:07
duplicate of #15

**Closed by rrrooommmaaa** 2018-12-23 13:07 UTC
Labels: Windows, bug
